// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	models "github.com/giicoo/maratWebSite/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddTest mocks base method.
func (m *MockRepo) AddTest(test models.Test) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTest", test)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTest indicates an expected call of AddTest.
func (mr *MockRepoMockRecorder) AddTest(test interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTest", reflect.TypeOf((*MockRepo)(nil).AddTest), test)
}

// AddUser mocks base method.
func (m *MockRepo) AddUser(user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockRepoMockRecorder) AddUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockRepo)(nil).AddUser), user)
}

// AddUserRes mocks base method.
func (m *MockRepo) AddUserRes(res models.UserResult, test_name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserRes", res, test_name)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserRes indicates an expected call of AddUserRes.
func (mr *MockRepoMockRecorder) AddUserRes(res, test_name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserRes", reflect.TypeOf((*MockRepo)(nil).AddUserRes), res, test_name)
}

// AddWord mocks base method.
func (m *MockRepo) AddWord(word models.Word) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWord", word)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWord indicates an expected call of AddWord.
func (mr *MockRepoMockRecorder) AddWord(word interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWord", reflect.TypeOf((*MockRepo)(nil).AddWord), word)
}

// GetTestByName mocks base method.
func (m *MockRepo) GetTestByName(name string) (models.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestByName", name)
	ret0, _ := ret[0].(models.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestByName indicates an expected call of GetTestByName.
func (mr *MockRepoMockRecorder) GetTestByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestByName", reflect.TypeOf((*MockRepo)(nil).GetTestByName), name)
}

// GetTests mocks base method.
func (m *MockRepo) GetTests() ([]*models.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTests")
	ret0, _ := ret[0].([]*models.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTests indicates an expected call of GetTests.
func (mr *MockRepoMockRecorder) GetTests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTests", reflect.TypeOf((*MockRepo)(nil).GetTests))
}

// GetUserByLogin mocks base method.
func (m *MockRepo) GetUserByLogin(login string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", login)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockRepoMockRecorder) GetUserByLogin(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockRepo)(nil).GetUserByLogin), login)
}

// GetWords mocks base method.
func (m *MockRepo) GetWords() ([]*models.Word, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWords")
	ret0, _ := ret[0].([]*models.Word)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWords indicates an expected call of GetWords.
func (mr *MockRepoMockRecorder) GetWords() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWords", reflect.TypeOf((*MockRepo)(nil).GetWords))
}

// GetWordsByNames mocks base method.
func (m *MockRepo) GetWordsByNames(words []*models.Word) ([]*models.Word, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWordsByNames", words)
	ret0, _ := ret[0].([]*models.Word)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWordsByNames indicates an expected call of GetWordsByNames.
func (mr *MockRepoMockRecorder) GetWordsByNames(words interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWordsByNames", reflect.TypeOf((*MockRepo)(nil).GetWordsByNames), words)
}
